apiVersion: v1
kind: Pod
metadata:
  name: pod-drop-none
spec:
  containers:
    - name: main
      image: fedora@sha256:5d5a02b873d298da9bca4b84440c5cd698b0832560c850d92cf389cef58bc549 # latest
      command: ["/bin/sleep", "999999"]

# kubectl exec -it pod-drop-none -- bash
# dnf -y install libcap-ng-utils
# pscap
## Notice net_raw capability
