---
# yamllint disable rule:line-length
name: Verify and Bump
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: Verify-and-Bump-${{ github.ref }}
  cancel-in-progress: true
jobs:
  security:
    permissions:
      contents: read
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
          token: ${{ github.token }}
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.8
      - run: |
          pip3 install checkov
      - run: sudo apt install -y jq
      - run: sudo apt install -y figlet
      - run: ./checker.sh
        shell: bash
